#!/bin/sh

# https://github.com/RichiH/vcsh/blob/main/doc/sample_hooks/post-init-setup-mr

mkdir -p $HOME/.config/mr/available.d

cat > $HOME/.config/mr/available.d/$VCSH_DIRECTORY.vcsh << EOF
[\$HOME/.config/vcsh/repo.d/$VCSH_DIRECTORY.git]
checkout =
    vcsh clone '$VCSH_GITURL/$VCSH_DIRECTORY-vcsh.git' '$VCSH_DIRECTORY'
    cd "\$MR_REPO"
    vcsh $VCSH_DIRECTORY remote add gitolite git@gitolite:tom/$VCSH_DIRECTORY-vcsh.git
skip = ! mylaptop
push = vcsh $VCSH_DIRECTORY push origin; vcsh $VCSH_DIRECTORY push gitolite || true
fixups = chmod -R go= $HOME/.config
EOF

# ln -s $HOME/.config/mr/available.d/$VCSH_DIRECTORY.vcsh $HOME/.config/mr/config.d/

echo "" && echo "be sure to '`tput setaf 1`move mr config from $HOME/.config/mr/available.d/$VCSH_DIRECTORY.vcsh to $HOME/.config/mr/vcsh.mrconfig`tput sgr0`'"
